export {default as Home} from './Home'
export {default as Cart} from './Cart'
export {default as Shop} from './Shop'
export {default as About} from './About'
export {default as ProductDetails} from './ProductDetails'
export {default as Search} from './Search'